# initial_recipes.py
initial_recipes = [
  {
    "title": "Tiramisu",
    "description": "Classic Italian coffee dessert",
    "ingredients": "Ladyfinger cookies, espresso, mascarpone cheese, eggs, sugar, cocoa powder, marsala wine",
    "instructions": "1. Make mascarpone cream. 2. Dip ladyfingers in espresso. 3. Layer cookies and cream. 4. Refrigerate 4 hours. 5. Dust with cocoa.",
    "prep_time": 30,
    "cook_time": 0,
    "servings": 8,
    "cuisine": "Italian",
    "difficulty": "Medium"
  },
  {
    "title": "Falafel",
    "description": "Crispy Middle Eastern chickpea fritters",
    "ingredients": "Chickpeas, onion, garlic, parsley, cilantro, cumin, coriander, salt, pepper, flour, baking powder, oil",
    "instructions": "1. Soak chickpeas overnight. 2. Blend herbs, chickpeas, onion, spices. 3. Form balls. 4. Fry until golden.",
    "prep_time": 20,
    "cook_time": 10,
    "servings": 4,
    "cuisine": "Middle Eastern",
    "difficulty": "Medium"
  },
  {
    "title": "Tom Yum (Vegetarian)",
    "description": "Spicy and sour Thai soup with mushrooms",
    "ingredients": "Vegetable broth, lemongrass, lime leaves, galangal, mushrooms, tomatoes, chili, lime juice, soy sauce, cilantro",
    "instructions": "1. Simmer broth with herbs. 2. Add mushrooms and tomatoes. 3. Season with lime juice and soy sauce.",
    "prep_time": 15,
    "cook_time": 15,
    "servings": 3,
    "cuisine": "Thai",
    "difficulty": "Easy"
  },
  {
    "title": "Spring Rolls",
    "description": "Fresh Vietnamese-style vegetable rolls",
    "ingredients": "Rice paper, lettuce, carrots, cucumber, herbs, rice noodles, peanut sauce",
    "instructions": "1. Soak rice paper. 2. Add vegetables and noodles. 3. Roll tightly. 4. Serve with sauce.",
    "prep_time": 20,
    "cook_time": 0,
    "servings": 6,
    "cuisine": "Vietnamese",
    "difficulty": "Easy"
  },
  {
    "title": "Cinnamon Rolls",
    "description": "Soft, fluffy rolls with cinnamon sugar",
    "ingredients": "Flour, butter, milk, sugar, cinnamon, yeast, cream cheese",
    "instructions": "1. Make dough. 2. Roll with cinnamon sugar. 3. Cut and bake. 4. Frost.",
    "prep_time": 30,
    "cook_time": 20,
    "servings": 12,
    "cuisine": "American",
    "difficulty": "Medium"
  },
  {
    "title": "Basque Cheesecake",
    "description": "Burnt cheesecake with creamy center",
    "ingredients": "Cream cheese, sugar, eggs, cream, flour, vanilla",
    "instructions": "1. Mix everything. 2. Bake at high heat until dark. 3. Cool completely.",
    "prep_time": 10,
    "cook_time": 35,
    "servings": 8,
    "cuisine": "Spanish",
    "difficulty": "Easy"
  },
  {
    "title": "Tofu with Noodles",
    "description": "Stir-fried tofu with vegetables and noodles",
    "ingredients": "Tofu, soy sauce, garlic, ginger, noodles, vegetables, sesame oil",
    "instructions": "1. Fry tofu. 2. Stir-fry vegetables. 3. Add noodles and sauce.",
    "prep_time": 15,
    "cook_time": 15,
    "servings": 2,
    "cuisine": "Asian",
    "difficulty": "Easy"
  },
  {
    "title": "Veggie Wraps",
    "description": "Fresh tortilla wraps with vegetables",
    "ingredients": "Tortillas, lettuce, tomato, cucumber, avocado, hummus",
    "instructions": "1. Spread hummus. 2. Add vegetables. 3. Roll.",
    "prep_time": 10,
    "cook_time": 0,
    "servings": 2,
    "cuisine": "Asian",
    "difficulty": "Easy"
  },
  {
    "title": "Churros",
    "description": "Crispy fried dough with cinnamon sugar",
    "ingredients": "Flour, water, butter, sugar, salt, oil, cinnamon",
    "instructions": "1. Mix dough. 2. Fry. 3. Coat in cinnamon sugar.",
    "prep_time": 15,
    "cook_time": 10,
    "servings": 6,
    "cuisine": "Spanish",
    "difficulty": "Easy"
  },
  {
    "title": "Lemon Bars",
    "description": "Tangy lemon custard on buttery crust",
    "ingredients": "Flour, butter, sugar, eggs, lemon juice, lemon zest",
    "instructions": "1. Bake crust. 2. Add filling. 3. Bake again.",
    "prep_time": 15,
    "cook_time": 20,
    "servings": 12,
    "cuisine": "American",
    "difficulty": "Easy"
  },

  {
    "title": "Vegetarian Pad Thai",
    "description": "Sweet-savory rice noodle stir-fry",
    "ingredients": "Rice noodles, tofu, tamarind sauce, egg, peanuts, bean sprouts, lime",
    "instructions": "1. Soak noodles. 2. Stir-fry tofu and egg. 3. Add noodles and sauce.",
    "prep_time": 20,
    "cook_time": 10,
    "servings": 2,
    "cuisine": "Thai",
    "difficulty": "Medium"
  },
  {
    "title": "Veggie Quesadillas",
    "description": "Crispy tortillas with cheese and vegetables",
    "ingredients": "Tortillas, cheese, peppers, onion, spinach",
    "instructions": "1. Sauté vegetables. 2. Fill tortillas with cheese. 3. Grill.",
    "prep_time": 10,
    "cook_time": 10,
    "servings": 2,
    "cuisine": "Mexican",
    "difficulty": "Easy"
  },
  {
    "title": "Shakshuka",
    "description": "Eggs poached in tomato sauce",
    "ingredients": "Tomatoes, peppers, onion, garlic, eggs, cumin, paprika",
    "instructions": "1. Cook vegetables with spices. 2. Add eggs. 3. Simmer until set.",
    "prep_time": 10,
    "cook_time": 20,
    "servings": 3,
    "cuisine": "Middle Eastern",
    "difficulty": "Easy"
  },
  {
    "title": "Paneer Butter Masala",
    "description": "Creamy Indian curry with paneer",
    "ingredients": "Paneer, tomatoes, cream, butter, spices, garlic, ginger",
    "instructions": "1. Cook tomatoes with spices. 2. Blend smooth. 3. Add paneer.",
    "prep_time": 15,
    "cook_time": 20,
    "servings": 3,
    "cuisine": "Indian",
    "difficulty": "Medium"
  },
  {
    "title": "Vegetarian Chili",
    "description": "Hearty bean and vegetable stew",
    "ingredients": "Beans, tomatoes, peppers, onion, garlic, chili powder, cumin",
    "instructions": "1. Sauté vegetables. 2. Add beans and tomatoes. 3. Simmer.",
    "prep_time": 15,
    "cook_time": 40,
    "servings": 4,
    "cuisine": "American",
    "difficulty": "Easy"
  },
  {
    "title": "Caprese Sandwich",
    "description": "Fresh mozzarella with tomato and basil",
    "ingredients": "Bread, mozzarella, tomato, basil, olive oil",
    "instructions": "1. Layer ingredients on bread.",
    "prep_time": 5,
    "cook_time": 0,
    "servings": 1,
    "cuisine": "Italian",
    "difficulty": "Easy"
  },
  {
    "title": "Greek Salad",
    "description": "Crisp salad with feta and olives",
    "ingredients": "Cucumber, tomato, red onion, feta, olives, olive oil",
    "instructions": "1. Chop vegetables. 2. Toss with oil and feta.",
    "prep_time": 10,
    "cook_time": 0,
    "servings": 2,
    "cuisine": "Greek",
    "difficulty": "Easy"
  },
  {
    "title": "Vegetable Lasagna",
    "description": "Layered pasta with ricotta and vegetables",
    "ingredients": "Lasagna noodles, ricotta, spinach, tomato sauce, mozzarella",
    "instructions": "1. Layer noodles, sauce, and cheese. 2. Bake.",
    "prep_time": 20,
    "cook_time": 40,
    "servings": 6,
    "cuisine": "Italian",
    "difficulty": "Medium"
  },
  {
    "title": "Mushroom Risotto",
    "description": "Creamy rice with mushrooms",
    "ingredients": "Arborio rice, mushrooms, broth, onion, butter, Parmesan",
    "instructions": "1. Cook onion. 2. Add rice. 3. Slowly add broth.",
    "prep_time": 10,
    "cook_time": 25,
    "servings": 3,
    "cuisine": "Italian",
    "difficulty": "Medium"
  },
  {
    "title": "Avocado Toast",
    "description": "Crispy toast with mashed avocado",
    "ingredients": "Bread, avocado, lemon, salt, pepper",
    "instructions": "1. Toast bread. 2. Spread avocado.",
    "prep_time": 5,
    "cook_time": 2,
    "servings": 1,
    "cuisine": "Fusion",
    "difficulty": "Easy"
  },
  {
    "title": "Vegetarian Sushi",
    "description": "Rice rolls with vegetables",
    "ingredients": "Rice, seaweed, cucumber, avocado, carrot",
    "instructions": "1. Make rice. 2. Roll with vegetables.",
    "prep_time": 25,
    "cook_time": 20,
    "servings": 4,
    "cuisine": "Japanese",
    "difficulty": "Medium"
  },
  {
    "title": "Pesto Pasta",
    "description": "Basil pesto tossed with pasta",
    "ingredients": "Pasta, basil, Parmesan, pine nuts, olive oil",
    "instructions": "1. Blend pesto. 2. Toss with pasta.",
    "prep_time": 10,
    "cook_time": 10,
    "servings": 2,
    "cuisine": "Italian",
    "difficulty": "Easy"
  },
  {
    "title": "Garlic Bread",
    "description": "Toasted bread with garlic butter",
    "ingredients": "Bread, butter, garlic, parsley",
    "instructions": "1. Spread garlic butter. 2. Toast.",
    "prep_time": 5,
    "cook_time": 10,
    "servings": 4,
    "cuisine": "Italian",
    "difficulty": "Easy"
  },
  {
    "title": "Vegetarian Burrito",
    "description": "Stuffed tortilla with beans and rice",
    "ingredients": "Tortilla, beans, rice, cheese, salsa",
    "instructions": "1. Fill tortilla. 2. Roll.",
    "prep_time": 10,
    "cook_time": 5,
    "servings": 2,
    "cuisine": "Mexican",
    "difficulty": "Easy"
  },
  {
    "title": "Gnocchi with Pesto",
    "description": "Soft gnocchi with basil pesto",
    "ingredients": "Gnocchi, basil pesto, Parmesan",
    "instructions": "1. Boil gnocchi. 2. Toss with pesto.",
    "prep_time": 5,
    "cook_time": 5,
    "servings": 2,
    "cuisine": "Italian",
    "difficulty": "Easy"
  },
  {
    "title": "Bruschetta",
    "description": "Toasted bread with tomatoes",
    "ingredients": "Tomato, basil, garlic, olive oil, bread",
    "instructions": "1. Mix tomatoes. 2. Top toast.",
    "prep_time": 10,
    "cook_time": 5,
    "servings": 4,
    "cuisine": "Italian",
    "difficulty": "Easy"
  },
  {
    "title": "Vegetarian Tacos",
    "description": "Crispy tacos filled with beans and veggies",
    "ingredients": "Taco shells, beans, lettuce, tomato, cheese",
    "instructions": "1. Fill tacos. 2. Serve fresh.",
    "prep_time": 10,
    "cook_time": 5,
    "servings": 3,
    "cuisine": "Mexican",
    "difficulty": "Easy"
  },
  {
    "title": "Caprese Salad",
    "description": "Fresh and simple Italian salad with tomatoes, mozzarella, and basil",
    "ingredients": "Tomatoes, fresh mozzarella, basil leaves, olive oil, salt, black pepper, balsamic glaze (optional)",
    "instructions": "1. Slice tomatoes and mozzarella. 2. Layer tomato, mozzarella, and basil on a plate. 3. Drizzle with olive oil and balsamic glaze. 4. Season with salt and pepper. 5. Serve immediately.",
    "prep_time": 10,
    "cook_time": 0,
    "servings": 2,
    "cuisine": "Italian",
    "difficulty": "Easy"
},
{
    "title": "Vegetable Stir-Fry",
    "description": "Quick and healthy stir-fried mixed vegetables",
    "ingredients": "Red bell pepper, yellow bell pepper, zucchini, carrot, broccoli florets, garlic, ginger, soy sauce, sesame oil, salt, pepper",
    "instructions": "1. Chop all vegetables. 2. Heat sesame oil in a pan. 3. Sauté garlic and ginger for 1 min. 4. Add vegetables and stir-fry 5-7 min until tender-crisp. 5. Add soy sauce, season with salt and pepper, and serve hot.",
    "prep_time": 10,
    "cook_time": 10,
    "servings": 2,
    "cuisine": "Asian",
    "difficulty": "Easy"
},
{
    "title": "Spinach and Feta Quiche",
    "description": "Savory vegetarian quiche with spinach and feta cheese",
    "ingredients": "Pre-made pie crust, fresh spinach, feta cheese, eggs, milk, onion, salt, pepper, nutmeg (optional)",
    "instructions": "1. Preheat oven to 180°C. 2. Sauté chopped onion until translucent. 3. Add spinach and cook until wilted, then cool. 4. Whisk eggs and milk, season with salt, pepper, and nutmeg. 5. Place spinach and onion on pie crust, crumble feta, pour egg mixture over. 6. Bake 30-35 min until set and golden. 7. Serve warm.",
    "prep_time": 15,
    "cook_time": 35,
    "servings": 4,
    "cuisine": "French",
    "difficulty": "Medium"
},
{
    "title": "Latvian Potato Pancakes (Vegetarian)",
    "description": "Crispy golden pancakes made from grated potatoes, a beloved Latvian comfort food, served with sour cream",
    "ingredients": "Potatoes, onion, eggs, flour, salt, pepper, oil for frying, sour cream (for serving)",
    "instructions": "1. Peel and grate potatoes and onion. 2. Squeeze out excess liquid. 3. Mix with eggs, flour, salt, and pepper to form batter. 4. Heat oil in pan. 5. Drop spoonfuls of batter and flatten slightly. 6. Fry until golden brown on both sides. 7. Serve hot with sour cream.",
    "prep_time": 20,
    "cook_time": 25,
    "servings": 4,
    "cuisine": "Latvian",
    "difficulty": "Easy"
},
{
    "title": "Latvian Beet Salad",
    "description": "Colorful vegetarian salad made with boiled beets, potatoes, carrots, and pickles, often served during holidays",
    "ingredients": "Beets, potatoes, carrots, pickles, peas, onion, sunflower oil, salt, pepper",
    "instructions": "1. Boil beets, potatoes, and carrots until tender. 2. Peel and dice all vegetables. 3. Chop pickles and onion finely. 4. Mix vegetables with peas in a large bowl. 5. Season with salt, pepper, and sunflower oil. 6. Chill before serving.",
    "prep_time": 30,
    "cook_time": 40,
    "servings": 6,
    "cuisine": "Latvian",
    "difficulty": "Medium"
}
]
